# Generated by Django 4.0.1 on 2022-01-14 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_comment_dislikes_comment_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-date',)},
        ),
    ]
