# Generated by Django 3.2.9 on 2021-12-21 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20211204_2323'),
        ('user', '0015_alter_profile_user'),
    ]

    operations = [
    ]
