# Generated by Django 3.2.9 on 2021-12-21 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20211212_2215'),
        ('user', '0016_merge_0005_auto_20211204_2323_0015_alter_profile_user'),
    ]

    operations = [
    ]
