# Generated by Django 3.0.14 on 2021-12-30 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_comment_date'),
        ('user', '0017_merge_20211221_0617'),
    ]

    operations = [
    ]
