# Generated by Django 3.2.9 on 2022-01-03 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20220102_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comment_content',
        ),
    ]
