# Generated by Django 3.2.5 on 2022-01-09 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20220109_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='department',
        ),
    ]
