# Generated by Django 3.2.9 on 2022-01-03 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
